[package]
edition = "2024"
name = "conveyor-balancer"
rust-version = "1.88"
version = "0.1.0"

[[bin]]
name = "conveyor-balancer"
path = "./src/bin/main.rs"
required-features = ["firmware"]
test = false
bench = false


[[bin]]
name = "simulator"
path = "src/bin/simulator.rs"
required-features = ["simulator"]

[features]
default = []
firmware = ["dep:blinksy-esp", "blinksy-esp/async", "blinksy-esp/esp32"]
simulator = ["dep:blinksy-desktop", "blinksy/async", "blinksy-desktop/async",
    "embassy-sync/std", "critical-section/std", "embassy-time/log", "dep:static_cell", "rand"]

[target.'cfg(not(target_os="none"))'.dependencies]
embassy-time = { version = "0.5.1", features = ["std"] }
embassy-executor = { version = "0.10.0", features = ["platform-std", "log", "executor-thread"] }

[target.xtensa-esp32-none-elf.dependencies]
esp-hal = { version = "~1.1.0", features = ["esp32", "log-04", "unstable"] }

esp-rtos = { version = "0.3.0", features = [
    "embassy",
    "esp-alloc",
    "esp32",
    "log-04",
] }

esp-bootloader-esp-idf = { version = "0.5.0", features = ["esp32", "log-04"] }

embassy-executor = { version = "0.10.0", features = ["log"] }
esp-alloc = { version = "0.10.0" }
esp-backtrace = { version = "0.19.0", features = [
    "esp32",
    "panic-handler",
    "println",
] }
esp-println = { version = "0.17.0", features = ["esp32", "log-04"] }




[dependencies]
log = "0.4.27"

critical-section = { version = "1.2.0" }
embassy-sync = { version = "0.8.0", features = ["log"] }
embassy-time = { version = "0.5.0", features = ["log"] }
embedded-hal-async = "1.0.0"
embedded-hal = { version = "1.0.0" }
circular-buffer = { version = "2", default-features = false }
moving_median = "0.4"
rand = { version = "0.10.2", optional = true }
blinksy = { version = "0.11.0", default-features = false, features = ["async"] }
blinksy-esp = { version = "0.11.0", optional = true }
static_cell = { version = "2.1.1", optional = true }
blinksy-desktop = { version = "0.11.0", optional = true }




[dev-dependencies]
embedded-hal-mock = { version = "0.11.1", features = ["default"] }

# For fine tuning these settings, please refer to https://doc.rust-lang.org/cargo/reference/profiles.html
[profile.dev]
# The default debug profile is too slow and too big for resource-constrained devices.
# Always build with some optimizations enabled.
opt-level = 2
incremental = false

[profile.release]
codegen-units = 1     # LLVM can perform better optimizations using a single thread
debug = 2     # prefer slower builds but better debugging experience
lto = 'fat'
opt-level = 's'


[patch.crates-io]
blinksy-desktop = { git = "https://github.com/ahdinosaur/blinksy" }
blinksy = { git = "https://github.com/ahdinosaur/blinksy" }
blinksy-esp = { git = "https://github.com/ahdinosaur/blinksy" }
